name: tasklist_commons
description: "A new Dart package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
